import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';
import { useEffect, useMemo, useRef } from 'react';
import type { Phase } from './workout';

// Static requires let Metro bundle the WAV files and give us asset module
// numbers that expo-audio accepts on both native (AVFoundation / ExoPlayer)
// and web. The files are generated by scripts/generate-audio.js.
const CUES = {
  keepalive: require('../../assets/audio/keepalive.wav') as number,
  high:      require('../../assets/audio/high.wav')      as number,
  low:       require('../../assets/audio/low.wav')       as number,
  tick:      require('../../assets/audio/tick.wav')      as number,
  finish:    require('../../assets/audio/finish.wav')    as number,
  chime:     require('../../assets/audio/chime.wav')     as number,
} as const;

type CueKey = keyof typeof CUES;

export async function configureAudioSession() {
  await setAudioModeAsync({
    playsInSilentMode: true,
    shouldPlayInBackground: true,
    interruptionMode: 'mixWithOthers',
  });
}

export function useWorkoutAudio() {
  const playersRef   = useRef<Partial<Record<CueKey, AudioPlayer>>>({});
  const keepAliveRef = useRef<AudioPlayer | null>(null);

  const getPlayer = (key: CueKey): AudioPlayer => {
    if (!playersRef.current[key]) {
      playersRef.current[key] = createAudioPlayer(CUES[key]);
    }
    return playersRef.current[key]!;
  };

  // Pre-load cue players so they're ready before the first sound fires.
  useEffect(() => {
    (['chime', 'tick', 'finish'] as const).forEach(getPlayer);
  }, []);

  const playCue = async (key: CueKey, volume = 1) => {
    try {
      const p = getPlayer(key);
      p.volume = volume;
      await p.seekTo(0);
      p.play();
    } catch (e) {
      console.warn('cue failed', key, e);
    }
  };

  const startKeepAlive = () => {
    if (keepAliveRef.current) return;
    const p = createAudioPlayer(CUES.keepalive);
    p.loop = true;
    p.volume = 0;
    p.play();
    keepAliveRef.current = p;
  };

  const stopKeepAlive = () => {
    keepAliveRef.current?.pause();
    keepAliveRef.current?.remove();
    keepAliveRef.current = null;
  };

  useEffect(() => () => {
    stopKeepAlive();
    Object.values(playersRef.current).forEach((p) => p?.remove());
    playersRef.current = {};
  }, []);

  return {
    playCue,
    playChime:  (volume = 1) => playCue('chime', volume),
    playTick:   (volume = 1) => playCue('tick', volume),
    playFinish: (volume = 1) => playCue('finish', volume),
    startKeepAlive,
    stopKeepAlive,
  };
}

export interface WorkoutAudioCues {
  onTransition(to: Phase | null): void;
  onCountdown(): void;
  onFinish(): void;
  onPreStartTick(): void;
  startKeepAlive(): void;
  stopKeepAlive(): void;
}

export function useWorkoutAudioCues(
  getSettings: () => { soundOff: boolean; soundCues: boolean; finalCountdownBeep: boolean; soundVolume: number }
): WorkoutAudioCues {
  const audio = useWorkoutAudio();
  const audioRef = useRef(audio);
  audioRef.current = audio;

  return useMemo(() => ({
    onTransition(to) {
      const s = getSettings();
      const cueEnabled = !s.soundOff && s.soundCues;
      if (to && cueEnabled) audioRef.current.playChime(s.soundVolume / 100);
    },
    onCountdown() {
      const s = getSettings();
      const beepEnabled = !s.soundOff && s.finalCountdownBeep;
      if (beepEnabled) audioRef.current.playTick(s.soundVolume / 100);
    },
    onFinish() {
      const s = getSettings();
      const cueEnabled = !s.soundOff && s.soundCues;
      if (cueEnabled) audioRef.current.playFinish(s.soundVolume / 100);
      audioRef.current.stopKeepAlive();
    },
    onPreStartTick() {
      const s = getSettings();
      const cueEnabled = !s.soundOff && s.soundCues;
      if (cueEnabled) audioRef.current.playTick(s.soundVolume / 100);
    },
    startKeepAlive: () => audioRef.current.startKeepAlive(),
    stopKeepAlive: () => audioRef.current.stopKeepAlive(),
  }), []); // eslint-disable-line react-hooks/exhaustive-deps -- stable: audioRef is a ref, getSettings is read at call-time
}
