import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';
import { useEffect, useMemo, useRef } from 'react';
import type { Phase } from './workout';
import type { Language } from './i18n';
import { speakPhase, speakComplete, speakPrepare, speakMidpoint, isSpeaking } from './speech';

// Static requires let Metro bundle the WAV files and give us asset module
// numbers that expo-audio accepts on both native (AVFoundation / ExoPlayer)
// and web. The files are generated by scripts/generate-audio.js.
const CUES = {
  keepalive: require('../../assets/audio/keepalive.wav') as number,
  high:      require('../../assets/audio/high.wav')      as number,
  low:       require('../../assets/audio/low.wav')       as number,
  tick:      require('../../assets/audio/tick.wav')      as number,
  finish:    require('../../assets/audio/finish.wav')    as number,
  chime:     require('../../assets/audio/chime.wav')     as number,
} as const;

type CueKey = keyof typeof CUES;

const MIDPOINT_POLL_MS    = 200;
const MIDPOINT_MAX_WAIT_MS = 4000;

export type AudioSettings = {
  soundOff: boolean;
  soundCues: boolean;
  finalCountdownBeep: boolean;
  soundVolume: number;
  voiceCues: boolean;
  minimalVoicePrompts: boolean;
  language: Language;
};

export async function configureAudioSession() {
  await setAudioModeAsync({
    playsInSilentMode: true,
    shouldPlayInBackground: true,
    interruptionMode: 'mixWithOthers',
  });
}

export interface WorkoutAudioCues {
  onTransition(to: Phase | null): void;
  onCountdown(): void;
  onPrepare(nextPhase: Phase): void;
  onFinish(): void;
  onPreStartTick(): void;
  onMidpoint(): void;
  startKeepAlive(): void;
  stopKeepAlive(): void;
}

// Each cue below reads a different subset of AudioSettings' toggles: soundOff is a
// global kill switch, soundCues/voiceCues/finalCountdownBeep gate specific cue
// categories independently of each other. Named here so each cue's actual gate is
// visible in one place instead of inlined ad hoc (and inconsistently) at each call
// site. NOTE: soundCues does not gate onCountdown (finalCountdownBeep-only) or
// onPrepare/onMidpoint (voiceCues-only) — preserved as-is from the prior inline
// logic; this consolidation does not change which flags gate which cue.
function soundCuesEnabled(s: AudioSettings): boolean {
  return !s.soundOff && s.soundCues;
}
function voiceCuesEnabled(s: AudioSettings): boolean {
  return !s.soundOff && s.voiceCues;
}
function finalCountdownBeepEnabled(s: AudioSettings): boolean {
  return !s.soundOff && s.finalCountdownBeep;
}

export function useWorkoutAudio(settings: AudioSettings): WorkoutAudioCues {
  const settingsRef = useRef(settings);
  settingsRef.current = settings;

  const playersRef   = useRef<Partial<Record<CueKey, AudioPlayer>>>({});
  const keepAliveRef = useRef<AudioPlayer | null>(null);

  const getPlayer = (key: CueKey): AudioPlayer => {
    if (!playersRef.current[key]) {
      playersRef.current[key] = createAudioPlayer(CUES[key]);
    }
    return playersRef.current[key]!;
  };

  useEffect(() => {
    (['chime', 'tick', 'finish'] as const).forEach(getPlayer);
  }, []);

  const playCue = async (key: CueKey, volume = 1) => {
    try {
      let p = getPlayer(key);
      p.volume = volume;
      await p.seekTo(0);
      p.play();
    } catch (e) {
      console.warn('cue failed', key, e);
      // Attempt recovery: recreate the player and retry once
      try {
        playersRef.current[key]?.remove();
        delete playersRef.current[key];
        const p = getPlayer(key);
        p.volume = volume;
        await p.seekTo(0);
        p.play();
      } catch (retryError) {
        console.warn('cue retry failed', key, retryError);
      }
    }
  };

  const startKeepAlive = async () => {
    if (keepAliveRef.current) return;
    try {
      await configureAudioSession();
      const p = createAudioPlayer(CUES.keepalive);
      p.loop = true;
      p.volume = 0;
      p.play();
      keepAliveRef.current = p;
    } catch (e) {
      console.warn('[Audio] startKeepAlive failed:', e);
    }
  };

  const isBeepPlaying = () => Object.values(playersRef.current).some(p => p?.playing);

  // Polls until no beep is playing and expo-speech reports idle, or the deadline passes —
  // whichever comes first — so the midpoint cue waits its turn instead of talking over
  // a phase-transition announcement or chime.
  const waitForCuesToClear = async (deadline: number): Promise<void> => {
    if (Date.now() >= deadline) return;
    const speechBusy = await isSpeaking();
    if (!isBeepPlaying() && !speechBusy) return;
    await new Promise(resolve => setTimeout(resolve, MIDPOINT_POLL_MS));
    return waitForCuesToClear(deadline);
  };

  const stopKeepAlive = () => {
    keepAliveRef.current?.pause();
    keepAliveRef.current?.remove();
    keepAliveRef.current = null;
  };

  useEffect(() => () => {
    stopKeepAlive();
    Object.values(playersRef.current).forEach((p) => p?.remove());
    playersRef.current = {};
  }, []);

  return useMemo<WorkoutAudioCues>(() => ({
    onTransition(to) {
      const s = settingsRef.current;
      if (!to || !soundCuesEnabled(s)) return;
      if (s.voiceCues) {
        speakPhase(to, s.language);
      } else {
        playCue('chime', s.soundVolume / 100);
      }
    },
    onCountdown() {
      const s = settingsRef.current;
      if (finalCountdownBeepEnabled(s)) playCue('tick', s.soundVolume / 100);
    },
    onPrepare(nextPhase) {
      const s = settingsRef.current;
      if (!voiceCuesEnabled(s) || s.minimalVoicePrompts) return;
      speakPrepare(nextPhase, s.language);
    },
    onFinish() {
      const s = settingsRef.current;
      if (soundCuesEnabled(s)) {
        if (s.voiceCues) {
          speakComplete(s.language, stopKeepAlive);
          return;
        } else {
          playCue('finish', s.soundVolume / 100);
        }
      }
      stopKeepAlive();
    },
    onPreStartTick() {
      const s = settingsRef.current;
      if (soundCuesEnabled(s)) playCue('tick', s.soundVolume / 100);
    },
    onMidpoint() {
      const s = settingsRef.current;
      if (!voiceCuesEnabled(s)) return;
      waitForCuesToClear(Date.now() + MIDPOINT_MAX_WAIT_MS).then(() => {
        speakMidpoint(settingsRef.current.language);
      });
    },
    startKeepAlive,
    stopKeepAlive,
  }), []); // stable: playCue/stopKeepAlive captured at mount but close over playersRef/keepAliveRef (refs, always current)
}
