import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';
import { useEffect, useRef } from 'react';

// Static requires let Metro bundle the WAV files and give us asset module
// numbers that expo-audio accepts on both native (AVFoundation / ExoPlayer)
// and web. The files are generated by scripts/generate-audio.js.
const CUES = {
  keepalive: require('../../assets/audio/keepalive.wav') as number,
  high:      require('../../assets/audio/high.wav')      as number,
  low:       require('../../assets/audio/low.wav')       as number,
  tick:      require('../../assets/audio/tick.wav')      as number,
  finish:    require('../../assets/audio/finish.wav')    as number,
  chime:     require('../../assets/audio/chime.wav')     as number,
} as const;

type CueKey = keyof typeof CUES;

export async function configureAudioSession() {
  await setAudioModeAsync({
    playsInSilentMode: true,
    shouldPlayInBackground: true,
    interruptionMode: 'mixWithOthers',
  });
}

export function useWorkoutAudio() {
  const playersRef   = useRef<Partial<Record<CueKey, AudioPlayer>>>({});
  const keepAliveRef = useRef<AudioPlayer | null>(null);

  const getPlayer = (key: CueKey): AudioPlayer => {
    if (!playersRef.current[key]) {
      playersRef.current[key] = createAudioPlayer(CUES[key]);
    }
    return playersRef.current[key]!;
  };

  const playCue = (key: CueKey) => {
    try {
      const p = getPlayer(key);
      // seekTo is async on iOS AVPlayer; play inside .then so it starts
      // from position 0, not from end-of-file (which silences short sounds).
      void p.seekTo(0).then(() => p.play());
    } catch (e) {
      console.warn('cue failed', key, e);
    }
  };

  const startKeepAlive = () => {
    if (keepAliveRef.current) return;
    const p = createAudioPlayer(CUES.keepalive);
    p.loop = true;
    p.volume = 0;
    p.play();
    keepAliveRef.current = p;
  };

  const stopKeepAlive = () => {
    keepAliveRef.current?.pause();
    keepAliveRef.current?.remove();
    keepAliveRef.current = null;
  };

  useEffect(() => () => {
    stopKeepAlive();
    Object.values(playersRef.current).forEach((p) => p?.remove());
    playersRef.current = {};
  }, []);

  return {
    playCue,
    playChime:  () => playCue('chime'),
    playTick:   () => playCue('tick'),
    playFinish: () => playCue('finish'),
    startKeepAlive,
    stopKeepAlive,
  };
}
